/** Static catalog of collection query capabilities — exposed as an MCP resource for agents. */
export const COLLECTION_SCHEMA_CATALOG = {
  common: {
    pagination: { page: "positive integer", limit: "positive integer, max 100" },
    sort: { sort: "allowlisted field per resource", direction: "asc | desc" },
    customFieldFilter:
      "filter via the custom_fields param keyed by numeric definition id; discover ids by querying the custom_field_definition resource (filter by entity: Deal | Contact | Company)",
    archivedFilter: "active | archived | all (deals, contacts, companies)",
  },
  deals: {
    endpoint: "GET /api/v1/deals",
    sort: [
      "created_at",
      "updated_at",
      "title",
      "value",
      "priority",
      "status",
      "expected_close_date",
      "position",
    ],
    filters: [
      "q (title search)",
      "status",
      "priority",
      "source",
      "pipeline (id)",
      "pipeline_stage (id)",
      "company (id)",
      "assignee (user id)",
      "value_min",
      "value_max",
      "close_date_from (YYYY-MM-DD)",
      "close_date_to (YYYY-MM-DD)",
      "archived",
      "custom_field[<id>]",
    ],
    create: "POST /api/v1/pipelines/:pipeline_id/deals (not POST /deals)",
    move: "PATCH /api/v1/deals/:id/move",
  },
  contacts: {
    endpoint: "GET /api/v1/contacts",
    sort: ["created_at", "updated_at", "email", "first_name", "last_name"],
    filters: [
      "q",
      "company (id)",
      "creator (user id)",
      "telegram",
      "archived",
      "custom_field[<id>]",
    ],
    companyLinks: "POST /api/v1/contacts/:contact_id/companies",
  },
  companies: {
    endpoint: "GET /api/v1/companies",
    sort: ["created_at", "updated_at", "name"],
    filters: [
      "q",
      "industry",
      "region",
      "company_size",
      "creator (user id)",
      "archived",
      "custom_field[<id>]",
    ],
  },
  members: {
    endpoint: "GET /api/v1/members",
    sort: ["joined_at", "role"],
    filters: ["role (owner | admin | member)"],
  },
  feed: {
    endpoint: "GET /api/v1/feed",
    sort: ["created_at"],
    filters: ["trackable_type + trackable_id", "action", "created_at_from", "created_at_to"],
  },
  enums: {
    dealStatus: ["open", "won", "lost"],
    dealPriority: ["none", "low", "medium", "high", "urgent"],
    dealSource: ["referral", "inbound", "outbound", "website", "conference", "other"],
    companyIndustry: [
      "technology",
      "finance",
      "healthcare",
      "education",
      "real_estate",
      "retail",
      "manufacturing",
      "media",
      "telecommunications",
      "energy",
      "transportation",
      "consulting",
      "legal",
      "non_profit",
      "government",
      "agriculture",
      "construction",
      "hospitality",
      "automotive",
      "pharmaceuticals",
    ],
    companyRegion: ["north_america", "emea", "apac", "latam", "global"],
    companySize: ["tiny", "small", "medium", "mid_market", "large", "enterprise"],
    pipelineStageType: ["standard", "won", "lost"],
    customizableTypes: ["Deal", "Contact", "Company"],
  },
} as const;
